services:
  postgres:
    container_name: postgres
    image: postgres:17.2
    command: "postgres -c 'config_file=/etc/postgresql/postgresql.conf'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    volumes:
      - './postgres/postgres.conf:/etc/postgresql/postgresql.conf'
      - './postgres/create-and-populate-outbox-table.sql:/create-and-populate-outbox-table.sql'

  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:3.0.8
    command: 'bin/pulsar standalone'
    user: root
    cap_add:
      - NET_ADMIN
    ports:
      - '7128:8080'
      - '6650:6650'
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_conf:/pulsar/conf


  debezium:
    container_name: debezium
    image: quay.io/debezium/server:3.1
    links:
      - 'postgres'
      - 'pulsar'
    ports:
      - '7080:8080'
    volumes:
      - './debezium:/debezium/config'
      - debezium_data:/debezium/data
    depends_on:
      - postgres
      - pulsar

volumes:
  postgres:
  pulsar_data:
  pulsar_conf:
  postgres_data:
  debezium_data:
